[package]
name = "grid-geom-util"
version = "0.1.0"
authors = [ "WeaverTVSC <weaver.imaginarium@proton.me>" ]
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
num-traits = "^0.2"
