[package]
name = "grid-geom-util"
version = "0.1.0"
authors = [ "Tuulikki Unelma" ]
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
num = "^0.4"

[dev-dependencies]
itertools = "^0.10"
